version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=postgres
      - PG_PORT=5432
      - PG_HOST=db
      - DEBUG=1
      - SECRET_KEY=foo
      - DJANGO_ALLOWED_HOSTS=*
    command:
      # poetry run python manage.py migrate &&
      poetry run python manage.py runserver 0.0.0.0:8000

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5445:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
